# This is a remoteSwitch example configuration file for a multi purpose gpio
# switch, configured as a 8x2 bandswitch running on an Orange Pi Zero.

# Configuration for connection to the NATS broker
[nats]
broker-url = "nats-server"
broker-port = 4222

# All remoteSwitches are at their core "switches". Here we specify the type
# and configuration key of the switch. In our case we select "multi_purpose_gpio".
[switch]
name = "mybandswitch"
type = "dummy_switch"

# This is the main configuration key. The name of the key is arbitrary, however
# it must be referenced corectly in the [switch] key.
[mybandswitch]
name = "8x4 Bandswitch"
# setting index = 2 means that it will be visualized in the GUI after all other
# switches with an index < 2 and before all other switched with an index > 2.
index = 1
# The exclusive parameter of a switch indicates if one terminal (button) can be
# selected on several ports at the same time. This parameter is
# relevant if the switch has more than one port. In our case, we have two ports
# and a terminal (antenna) can only be assigned to one port. So exclusive must
# be set to true.
exclusive = true
# ports contains a list of keys refering to the ports of this switch. Our 8x2
# bandswitch has the 2 (input) ports "port_a" and "port_b". The key names can
# be arbitrary, as long as the key exists in this config file.
ports = ["port_a", "port_b", "port_c", "port_d"]

# First port for myBandswitch
[port_a]
name = "STN1"
# index sets the order of this port for graphical representation in the GUI.
index = 1
# the exclusive parameter ensures that only one terminal can be set at any time
# on this port. With a 8x2 bandswitch we can only select one terminal (antenna)
# at a time. So exclusive must be set to true.
exclusive = true
# terminals contains a list of keys refering to the terminals of this port. The
# name of the keys can be arbitray, as long as they exist in this config file.
terminals = ["a_160m", "a_80m", "a_40m", "a_20m", "a_15m", "a_10m", "a_6m", "a_WARC"]

# Second port for myBandswitch
[port_b]
name = "STN2"
index = 2
exclusive = true
terminals = ["b_160m", "b_80m", "b_40m", "b_20m", "b_15m", "b_10m", "b_6m", "b_WARC"]

[port_c]
name = "STN3"
index = 3
exclusive = true
terminals = ["c_160m", "c_80m", "c_40m", "c_20m", "c_15m", "c_10m", "c_6m", "c_WARC"]

[port_d]
name = "STN4"
index = 4
exclusive = true
terminals = ["d_160m", "d_80m", "d_40m", "d_20m", "d_15m", "d_10m", "d_6m", "d_WARC"]

# Terminals (GPIO Pins) for port_a
[a_160m]
name = "160m"
index = 0

[a_80m]
name = "80m"
index = 1

[a_40m]
name = "40m"
index = 2

[a_20m]
name = "20m"
index = 3

[a_15m]
name = "15m"
index = 4

[a_10m]
name = "10m"
index = 5

[a_6m]
name = "6m"
index = 6

[a_WARC]
name = "WARC"
index = 7

# Terminals for port_b
[b_160m]
name = "160m"
index = 0

[b_80m]
name = "80m"
index = 1

[b_40m]
name = "40m"
index = 2

[b_20m]
name = "20m"
index = 3

[b_15m]
name = "15m"
index = 4

[b_10m]
name = "10m"
index = 5

[b_6m]
name = "6m"
index = 6

[b_WARC]
name = "WARC"
index = 7

# Terminals for port_c
[c_160m]
name = "160m"
index = 0

[c_80m]
name = "80m"
index = 1

[c_40m]
name = "40m"
index = 2

[c_20m]
name = "20m"
index = 3

[c_15m]
name = "15m"
index = 4

[c_10m]
name = "10m"
index = 5

[c_6m]
name = "6m"
index = 6

[c_WARC]
name = "WARC"
index = 7

# Terminals for port_c
[d_160m]
name = "160m"
index = 0

[d_80m]
name = "80m"
index = 1

[d_40m]
name = "40m"
index = 2

[d_20m]
name = "20m"
index = 3

[d_15m]
name = "15m"
index = 4

[d_10m]
name = "10m"
index = 5

[d_6m]
name = "6m"
index = 6

[d_WARC]
name = "WARC"
index = 7
